-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Nov 27, 2025 at 03:14 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `nusakata_db`
--

-- --------------------------------------------------------

--
-- Table structure for table `kamus_arkaik`
--

CREATE TABLE `kamus_arkaik` (
  `perkataan` varchar(100) NOT NULL,
  `ayat` text DEFAULT NULL,
  `transkripsi_fonetik` varchar(100) DEFAULT NULL,
  `cadangan_kegunaan` text DEFAULT NULL,
  `makna` text DEFAULT NULL,
  `audio` varchar(150) DEFAULT NULL,
  `gambar` varchar(150) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `kamus_arkaik`
--

INSERT INTO `kamus_arkaik` (`perkataan`, `ayat`, `transkripsi_fonetik`, `cadangan_kegunaan`, `makna`, `audio`, `gambar`) VALUES
('aghlaf', 'Golongan aghlaf sukar menerima seruan dakwah kerana pegangan lama yang masih kuat berakar. Pendakwah zaman silam menghadapi cabaran besar ketika menyebarkan agama Islam kepada golongan aghlaf', '[ɑɣּlɑf]', 'Sesuai digunakan dalam konteks agama dan dakwah Islam, khususnya dalam penulisan sejarah Islam atau teks keagamaan klasik. Perkataan ini menggambarkan golongan yang keras hati atau sukar menerima ajaran baru kerana pegangan lama yang kuat. Ia tidak sesuai digunakan dalam bahasa komunikasi moden harian, namun amat relevan dalam penulisan ilmiah, karya sastera klasik, atau teks hikayat yang menyentuh aspek keagamaan dan perjuangan dakwah.', '1 orang yang tidak bersunat; 2 orang bukan Islam', 'aghlaf.mp3', 'aghlaf.jpg'),
('akah', 'Seorang nelayan menjerat seekor akah yang besar tatkala laut sedang bergelora pada malam purnama', '[ɑ.kɑh]', 'Sesuai digunakan dalam konteks maritim dan alam semula jadi, khususnya dalam penulisan sastera tradisional atau hikayat yang menggambarkan kehidupan nelayan dan laut. Perkataan ini merujuk kepada sejenis penyu, dan penggunaannya lebih tepat dalam naratif berkaitan laut, pantai, atau kisah perburuan hidupan laut. Tidak sesuai digunakan dalam pertuturan moden kerana telah jarang digunakan dalam bahasa harian.', 'Sejenis penyu', 'akah.mp3', 'akah.jpg'),
('anca', 'Segala usaha hulubalang itu terhenti jua, dek anca yang bersarang di benak fikirannya, membutakan jalan ikhtiar.', '[ɑn. t§ɑ]', 'Sesuai digunakan dalam konteks sastera klasik, hikayat, atau penulisan yang menggambarkan perasaan, cabaran, dan konflik dalaman watak. Istilah ini membawa makna rintangan atau kerugian akibat kekeliruan, maka penggunaannya lebih tepat dalam ayat berunsur metafora atau emosi. Dalam bahasa moden, perkataan ini boleh dijadikan unsur gaya bahasa bagi menunjukkan kekangan fikiran atau halangan psikologi.', '1 rintangan; 2 kerugian krn kekeliruan dsb', 'anca.mp3', 'anca.jpg'),
('bad', 'Tatkala fajar menyingsing, bad timur berpuput lembut menyapa wajah sang puteri di anjung istana', '[bɑd]', 'Sesuai digunakan dalam konteks sastera klasik, hikayat, atau karya puisi tradisional yang menggambarkan suasana alam, pergerakan angin, atau perubahan waktu siang dan malam. Maknanya sebagai angin menjadikannya sesuai digunakan dalam deskripsi puitis atau simbolik, khususnya bagi menggambarkan suasana tenang atau perubahan cuaca. Dalam konteks moden, penggunaannya lebih bersifat estetik dan kiasan, bukan dalam komunikasi harian.', 'angin', 'bad.mp3', 'bad.jpg'),
('bagal', 'Maka datanglah seorang hulubalang membawa pedang bagal rupanya, hingga gentarlah segala lawan yang memandang', '[bɑ.gɑl]', 'Sesuai digunakan dalam penulisan sastera lama, hikayat peperangan, atau karya yang menggambarkan kekuatan dan ketegasan watak. Maknanya yang merujuk kepada sesuatu yang terlampau besar, panjang, atau kasar menunjukkan sifat gagah, lasak, atau menakutkan. Sesuai digunakan dalam konteks fizikal (seperti senjata) atau sifat perwatakan (kasar, garang) dalam teks naratif tradisional. Dalam bahasa moden, penggunaannya lebih terhad dan bersifat gaya arkaik.', '1 terlampau besar dan panjang; 2 kasar', 'bagal.mp3', 'bagal.jpg'),
('beloh', 'Janganlah engkau bertutur sembarangan, kelak disangka orang akan beloh budi dan dangkal fikir', '[be.loh]', 'Sesuai digunakan dalam konteks maritim atau kisah nelayan. Lazim dalam hikayat laut atau cerita rakyat yang menggambarkan kehidupan pesisir pantai.', 'bodoh', 'beloh.mp3', 'beloh.jpg'),
('cakela', 'di hujung kota, berdirilah sebuah cakela tempat hina yang menjadi aib pada negeri dan buah mulut sekalian orang', NULL, 'Sesuai digunakan dalam penulisan sastera klasik atau hikayat yang menggambarkan suasana sosial dan moral masyarakat lama. Kata ini boleh digunakan dalam kajian budaya, sejarah sosial, atau teks naratif moral yang menonjolkan unsur kehinaan atau kejatuhan akhlak masyarakat.', 'bangunan yg khusus untuk aktiviti pelacuran dan kadang-kadang sbg tempat tinggal pelacuran; rumah cakela', 'cakela.mp3', 'cakela.jpg'),
('dadi', 'Di pagi yang damai, nenek menyajikan dadi segar hasil susunya, penawar kerinduan jiwa dan raga', '[dɑ.di]', 'Sesuai digunakan dalam konteks budaya tradisional atau gastronomi Melayu. Kata ini boleh digunakan dalam penulisan sejarah makanan atau karya sastera yang menggambarkan suasana kampung dan kehidupan masyarakat lama, terutamanya berkait dengan hasil tenusu dan masakan tradisional.', 'dadih', 'dadi.mp3', 'dadi.jpg'),
('dati', 'Di penjuru kubu, menjulang tinggi dati bertingkat-tingkat sebagai benteng pengawal yang setia.', '[dɑ.ti]', 'Sesuai digunakan dalam penulisan sejarah, karya epik, atau hikayat peperangan untuk menggambarkan struktur pertahanan zaman silam. Istilah ini juga boleh digunakan dalam kajian seni bina tradisional atau ketenteraan Melayu lama, khususnya apabila menerangkan aspek kubu atau istana.', 'Menara kecil bertingkat-tingkat yg mengunjur di penjuru kubu', 'dati.mp3', 'dati.jpg'),
('datia', 'Datia, raksasa yang menakutkan, mengaum di hutan rimba tanpa berbatas', '[dɑ.ti.ɑ]', 'Sesuai digunakan dalam hikayat, cerita rakyat, atau teks sastera tradisional yang mengandungi unsur mitos dan legenda. Istilah ini boleh dimanfaatkan dalam kajian kesusasteraan Melayu klasik atau perbandingan mitologi Nusantara, bagi menunjukkan pengaruh kepercayaan animisme dan simbolisme dalam naratif lama.', 'Sejenis raksasa', 'datia.mp3', 'datia.jpg'),
('dol', '1. Dentuman dol menggema di medan perang, menggetarkan jiwa para pahlawan 2. Tiang dol berdiri teguh di tengah badai, menahan gelora laut nan ganas', '[dol]', 'Sesuai digunakan dalam hikayat peperangan, sastera rakyat, atau teks sejarah maritim Melayu. Dalam konteks moden, istilah ini boleh dimanfaatkan untuk kajian etnomuzikologi (alat muzik tradisional) atau istilah kelautan Melayu lama, khususnya apabila menerangkan budaya dan peralatan zaman silam.', 'Dol 1: gendang ; dol 2: tiang kapal', 'dol.mp3', 'dol.jpg'),
('dor', 'dan Megido dengan segala daerahnya dan Dor dengan segala daerahnya', '[dor]', 'Sesuai digunakan dalam teks keagamaan, hikayat sejarah, atau terjemahan teks klasik yang merujuk kepada nama tempat atau daerah. Istilah ini boleh dikekalkan dalam konteks kajian toponimi (nama tempat) atau terjemahan teks sejarah agama yang mengekalkan bentuk asal nama kuno.', 'daur', 'dor.mp3', 'dor.jpg'),
('gita', 'Gita merdu bergema di istana, menghibur raja dan para pembesar dengan lagu nan indah', '[gi.tɑ]', 'Sesuai digunakan dalam karya sastera klasik, puisi, dan hikayat istana bagi menggambarkan suasana harmoni atau hiburan diraja. Dalam konteks moden, istilah ini juga boleh digunakan secara puitis dalam puisi kontemporari atau muzik tradisional Melayu untuk menggantikan perkataan \"lagu\".', 'Nyanyian atau lagu', 'gita.mp3', 'gita.jpg'),
('gul', 'Gul merekah indah di taman istana, harum mewangi memikat hati sang puteri', '[gul]', 'Sesuai digunakan dalam hikayat percintaan, karya sastera klasik, atau puisi Melayu tradisional untuk melambangkan keindahan, cinta, dan kelembutan. Dalam konteks moden, perkataan ini boleh digunakan dalam penulisan kreatif atau nama produk berunsur tradisional dan estetika Melayu.', 'Bunga ros atau bunga mawar', 'gul.mp3', 'gul.jpg'),
('haud', 'Haud yang sejuk menjadi tempat persemadian para wali yang mulia, penuh keberkatan dan ketenangan', '[hɑ.ud]', 'Sesuai digunakan dalam karya keagamaan, hikayat atau teks bernuansa spiritual dan mistik, khususnya untuk menggambarkan tempat suci, tenang, atau berkat. Dalam konteks moden, perkataan ini boleh digunakan secara puitis atau simbolik bagi menggambarkan ketenangan batin atau tempat perhentian rohani.', 'kolam', 'haud.mp3', 'haud.jpg'),
('hindu', 'Dahulu kala, orang Hindu kita merentas alam menyemai benih kebijaksanaan', '[hin.du]', 'Sesuai digunakan dalam teks sejarah, hikayat asal-usul bangsa, atau kajian budaya, menggambarkan keturunan atau generasi terdahulu masyarakat Melayu purba. Dalam konteks moden, istilah ini boleh digunakan secara sejarah atau antropologi, bukan keagamaan, untuk menekankan warisan dan akar ketamadunan Nusantara.', 'nenek moyang', 'hindu.mp3', 'hindu.jpg'),
('injili', 'Hal yg berkenaan kitab Injil, atau menurut kitab Injil', '[iɲ.dʒi.li]', 'Injili itu menjadi pegangan suci dalam menuntun jiwa ke jalan kebenaran', 'Sesuai digunakan dalam bidang keagamaan atau kajian teologi, khususnya dalam naskhah Melayu klasik, namun tidak sesuai digunakan dalam konteks rasmi kerajaan kerana membawa makna khusus agama Kristian.', 'injili.mp3', 'injili.jpg'),
('istima', 'Pertimbangan, pendapat dsb yg baik', '[is.ti.mɑʔ]', 'Berpeganglah pada istima yang jernih agar keputusan terbit dari hikmah', 'Sesuai digunakan dalam penulisan akademik atau teks klasik berkaitan kepimpinan dan kebijaksanaan Melayu, tetapi kurang sesuai dalam bahasa moden kerana telah digantikan dengan istilah seperti pendapat atau pertimbangan.', 'istima.mp3', 'istima.jpg'),
('jelit', '[Menjelitkan, dijelitkan, jelitkan] 1 menjadikan (sst yg berjarak) bertaut semlula; 2 menyelitkan (sst) di antara dua benda atau di celah-celahnya', '[dʒe.lit]', 'Tangan mahir jelit benang sutera ke dalam kain tenunan lama', 'Sesuai digunakan dalam bidang seni tekstil dan kesusasteraan Melayu tradisional bagi menggambarkan tindakan menyambung atau menyelit dengan teliti, namun jarang digunakan dalam bahasa moden.', 'jelit.mp3', 'jelit.jpg'),
('jetis', '[menjetis] berbunyi kuat spt bunyi mercun', '[dʒe.tis]', 'Suara jetis menggema di malam sunyi, memecah ketenangan desa', 'Sesuai digunakan dalam karya sastera Melayu klasik atau puisi untuk menggambarkan suasana bising yang kuat, namun tidak sesuai dalam konteks rasmi atau teknikal kerana penggunaannya bersifat peribumi dan ekspresif.', 'jetis.mp3', 'jetis.jpg'),
('jitok', 'tengkuk', '[dʒe.toʔ]', 'Datuk tua mengusap jitoknya yang tegang setelah seharian bekerja di ladang', 'Sesuai digunakan dalam kajian dialektologi dan karya sastera rakyat yang mengekalkan keaslian bahasa daerah, tetapi tidak sesuai dalam konteks rasmi kerana bentuk bakunya ialah tengkuk.', 'jitok.mp3', 'jitok.jpg'),
('kahaf', 'Gua yg besar', '[kɑ.hɑf]', 'Para pengembara berteduh di dalam kahaf yang gelap demi menghindar dari hujan lebat', 'Sesuai digunakan dalam penulisan keagamaan, sejarah Islam, atau karya berunsur ketuhanan kerana berasal daripada istilah Arab, tetapi kurang sesuai dalam penggunaan harian moden.', 'kahaf.mp3', 'kahaf.jpg'),
('kala', 'Jerat', '[kɑ.lɑ]', 'Pemburu memasang kala di celah semak untuk menangkap binatang buruan', 'Sesuai digunakan dalam konteks kesusasteraan rakyat atau teks etnografi yang membincangkan budaya memburu masyarakat tradisional, namun tidak relevan dalam penggunaan bahasa Melayu kontemporari.', 'kala.mp3', 'kala.jpg'),
('kanjus', 'lokap', '[kɑɲ.dʒus]', 'Para banduan disimpan rapi di dalam kanjus yang gelap dan sempit', 'Sesuai digunakan dalam karya kreatif atau kajian linguistik yang meneliti kosa kata arkaik berkaitan sistem hukuman lama, tetapi tidak sesuai dalam konteks undang-undang moden kerana telah digantikan dengan istilah lokap atau penjara.', 'kanjus.mp3', 'kanjus.jpg'),
('kena', 'Kata ganti nama diri kedua', '[kə.nɑ]', 'Kena telah pergi menziarahi datuk di kampung halaman pada petang tadi', 'Sesuai digunakan dalam naskhah Melayu klasik atau kajian linguistik sejarah bagi menunjukkan bentuk lama kata ganti nama diri kedua, namun tidak sesuai dalam bahasa Melayu moden kerana telah digantikan dengan kata engkau atau kamu.', 'kena.mp3', 'kena.jpg'),
('lahang', 'Nira atau tuak', '[lɑ.hɑŋ]', 'Setiap petang, penduduk kampung berkumpul menikmati lahang yang segar dari pohon nipah', 'Sesuai digunakan dalam penulisan etnografi, sastera rakyat, atau dokumentasi budaya tempatan berkaitan makanan dan minuman tradisional Melayu, tetapi tidak sesuai dalam konteks rasmi moden kecuali untuk tujuan budaya.', 'lahang.mp3', 'lahang.jpg'),
('lazat', '(bkn penyakit) teruk', '[lɑ.zɑt]', 'Walaupun badan terasa lemah, itu hanyalah sakit lazat yang mudah disembuhkan', 'Sesuai digunakan dalam teks klasik yang berunsur perubatan atau kesusasteraan lama bagi menggambarkan tahap kesakitan yang teruk, namun makna ini tidak lagi digunakan dalam bahasa kontemporari yang menekankan maksud \"sedap\".', 'lazat.mp3', 'lazat.jpg'),
('lemena', 'Baju besi yg dipakai utk berperang', '[lə.me.nɑ]', 'Pahlawan agung itu menggayakan lemena besi, bersiap sedia menyambut peperangan.', 'Sesuai digunakan dalam penulisan sejarah, kesusasteraan epik, atau karya fantasi Melayu yang menggambarkan peperangan tradisional, namun tidak sesuai dalam komunikasi moden kerana telah digantikan dengan istilah perisai badan atau baju zirah.', 'lemena.mp3', 'lemena.jpg'),
('mahaduta', 'Mahaduta dari negeri seberang tiba membawa surat salam raja yang mulia', '[mɑ.hɑ.du.tɑ]', 'Sesuai digunakan dalam teks sejarah, diplomasi klasik, atau karya sastera Melayu lama bagi menggambarkan utusan diraja bertaraf tinggi; tidak sesuai dalam komunikasi rasmi moden kerana kini digantikan dengan istilah duta besar.', 'Duta besar', 'mahaduta.mp3', 'mahaduta.jpg'),
('manat', 'Tetap mengenai janji atau persetujuan dalam mesyuarat', '[mɑ.nɑt]', 'Segala perkara yang diputuskan dalam mesyuarat itu telah mencapai manat yang dipersetujui bersama', 'Sesuai digunakan dalam konteks pentadbiran tradisional atau perbincangan adat Melayu bagi menggambarkan kata sepakat dalam keputusan mesyuarat, namun tidak digunakan dalam bahasa moden yang lebih memilih istilah resolusi atau persetujuan.', 'manat.mp3', 'manat.jpg'),
('milu', 'Tangan petani sibuk menuai milu di ladang yang terbentang luas', '[mi.lu]', 'Sesuai digunakan dalam penulisan etnolinguistik, pertanian tradisional, atau karya sastera lama untuk menunjukkan kosa kata tempatan bagi tanaman jagung, tetapi kurang sesuai dalam konteks sains moden yang memerlukan istilah standard.', 'jagung', 'milu.mp3', 'milu.jpg'),
('nawa', 'Para hulubalang berdiri teguh berbaris seramai nawa, siap sedia mempertahankan istana', '[nɑ.wɑ]', 'Sesuai digunakan dalam teks klasik, puisi, atau karya sejarah bagi menggambarkan bilangan sembilan dalam gaya puitis atau simbolik, namun tidak sesuai dalam komunikasi semasa kerana bentuk moden sembilan lebih umum digunakan.', 'Bil sembilan', 'nawa.mp3', 'nawa.jpg'),
('nyarik', 'Teriakan panglima itu nyarik membelah hutan, menggema ke seluruh pelusuk desa.', '[ɲɑ.riʔ]', 'Sesuai digunakan dalam karya sastera atau hikayat Melayu lama bagi menggambarkan bunyi atau suara yang lantang dan bergaung, namun kurang sesuai digunakan dalam bahasa moden kecuali dalam konteks puitis atau dramatik.', '(bkn suara, bunyi dsb) kuat, jelas dan bernada tinggi; nyaring', 'nyarik.mp3', 'nyarik.jpg'),
('obros', 'Obros itu memimpin barisan pahlawan dengan penuh keberanian di medan perang', '[ob.ros]', 'Sesuai digunakan dalam teks sejarah ketenteraan atau karya sastera tradisional untuk merujuk pangkat tentera zaman dahulu, tetapi tidak sesuai dalam konteks ketenteraan moden kerana istilah ini telah digantikan dengan sistem pangkat rasmi seperti Leftenan Kolonel.', 'Pegawai tentera yg berpangkat Leftenan Kolonel', 'obros.mp3', 'obros.jpg'),
('om', 'Dengan lafaz om, para dukun membuka mantera sakti agar segala doa dimakbulkan', '[om]', 'Sesuai digunakan dalam konteks kajian antropologi, budaya, atau kepercayaan tradisional bagi menggambarkan unsur ritual dan mantera dalam masyarakat lama, namun tidak sesuai dalam penulisan akademik moden kecuali sebagai bahan kajian budaya atau agama.', 'Seruan atau doa pembukaan mantera; ong', 'om.mp3', 'om.jpg'),
('pancal', 'Pedang pusaka itu ditempa dari besi pancal, memancarkan kilau yang menggentar musuh', '[pɑɲ.t§ɑl]', 'Sesuai digunakan dalam teks sejarah, kesusasteraan, atau penulisan teknikal tradisional berkaitan pandai besi dan senjata Melayu lama, tetapi tidak sesuai dalam bahasa moden kecuali untuk menggambarkan proses pembuatan senjata secara tradisi.', 'pancalogam', 'pancal.mp3', 'pancal.jpg'),
('pengluru', 'Dalam gegak gempita medan tempur, pengluru bersimpang-siur membelah udara', '[peŋ.lu.ru]', 'Sesuai digunakan dalam karya sastera epik atau hikayat peperangan Melayu untuk menggambarkan suasana pertempuran yang dramatik, namun tidak sesuai digunakan dalam konteks moden kerana telah digantikan dengan istilah peluru dalam bahasa standard.', 'peluru', 'pengluru.mp3', 'pengluru.jpg'),
('rampang', 'Hamba menjadi rampang mendengar fitnah yang ditabur sesuka hati di balai permesyuaratan itu', '[rɑm.pɑɲ]', 'Sesuai digunakan dalam karya kesusasteraan tradisional atau penulisan yang menonjolkan emosi dan ekspresi perasaan marah secara klasik, tetapi kurang sesuai dalam komunikasi harian moden kecuali untuk tujuan gaya bahasa atau penulisan kreatif.', 'Berasa marah atau berang', 'rampang.mp3', 'rampang.jpg'),
('rana', 'Rana berterbangan di udara, menyapa perisai dan tubuh, menyemarakkan sengketa di padang perang', '[rɑ.nɑ]', 'Sesuai digunakan dalam teks sejarah, hikayat peperangan, atau puisi epik Melayu yang menggambarkan suasana medan tempur, namun tidak sesuai dalam konteks moden kecuali sebagai unsur gaya bahasa puitis atau dalam analisis sastera tradisional.', '1 peperangan; 2 medan perang', 'rana.mp3', 'rana.jpg'),
('ruban', 'Ruban yang timbul di permukaan minyak kelapa itu dikaut perlahan untuk dijadikan ramuan penghidang juadah warisan', '[ru.bɑn]', 'Sesuai digunakan dalam karya yang berkaitan dengan warisan kulinari atau budaya tradisional Melayu, khususnya dalam konteks penyediaan makanan berasaskan kelapa, tetapi kurang sesuai dalam penggunaan harian moden kerana istilah ini sudah jarang digunakan.', 'air yg berupa buih yg terdapat di atas bahagian minyak kelapa semasa ditanak', 'ruban.mp3', 'ruban.jpg'),
('sadat', 'Hati', '[sɑ.dɑt]', 'Seorang pemuda menenangkan sadatnya sebelum membuat keputusan penting', 'Sesuai digunakan dalam konteks kesusasteraan klasik atau puisi Melayu bagi menggambarkan emosi dalaman atau hati seseorang, jarang digunakan dalam bahasa moden.', 'sadat.mp3', 'sadat.jpg'),
('sagar', 'Sagar yang mengeras dalam tempayan tembikar itu dipatah-patahkan untuk dijadikan manisan pembuka selera', '[sɑ.gɑr]', 'Sesuai digunakan dalam bidang gastronomi tradisional atau penulisan sastera yang menggambarkan suasana dapur zaman silam, dan sesuai dimasukkan dalam karya Melayu klasik atau teks budaya; namun tidak sesuai dalam komunikasi moden kerana telah digantikan dengan istilah gula atau sakar.', 'Gula yg telah dicairkan dan mengeras semula apb sejuk; sakar', 'sagar.mp3', 'sagar.jpg'),
('suak', 'Segala ikhtiar tuanku menawan kota seberang berakhir dengan suak yang memilukan hati seisi balai', '[su.wɑʔ]', 'Sesuai digunakan dalam karya sastera lama, hikayat, atau puisi klasik bagi menggambarkan kegagalan atau kekalahan dengan gaya bahasa puitis, tetapi tidak sesuai digunakan dalam penulisan formal moden kerana maknanya kurang difahami oleh masyarakat masa kini.', 'Tidak berjaya atau gagal', 'suak.mp3', 'suak.jpg'),
('tadia', 'Sudah tiba', '[tɑ.di.ɑ]', 'Para tetamu tadia di balai kerajaan menunggu kehadiran raja', 'Sesuai digunakan dalam teks klasik Melayu atau hikayat untuk menunjukkan ketibaan, jarang digunakan dalam bahasa moden.', 'tadia.mp3', 'tadia.jpg'),
('tais', 'Busana permaisuri ternoda dengan lumpur, tampak tais di mata hadirin yang hadir ke majlis persantapan diraja.', '[tɑ.is]', 'Sesuai digunakan dalam karya sastera klasik atau teks naratif lama untuk menggambarkan keadaan kotor atau ternoda dengan gaya bahasa halus; tidak sesuai dalam penulisan moden kerana kini digantikan dengan perkataan seperti kotor atau bernoda.', '1. (bkn pakaian, badan dll) tidak bersih atau kotor; 2. (bkn kencing) tidak tumpah kerana terkena jangkitan', 'tais.mp3', 'tais.jpg'),
('tasa', 'Pinggan tasa dari warisan datuk itu masih menghiasi para di anjung rumah pusaka', '[tɑ.sɑ]', 'Sesuai digunakan dalam konteks perbincangan seni warisan, sejarah material budaya, atau karya sastera yang menonjolkan peralatan tradisional Melayu; tidak sesuai dalam komunikasi harian moden kerana istilah ini sudah jarang digunakan di luar konteks sejarah atau muzium.', 'Tangsa', 'tasa.mp3', 'tasa.jpg'),
('togan', 'Tiada siapa pun menogani bayang laksamana yang hilang di balik kabus senja itu', '[to.gɑn]', 'Sesuai digunakan dalam karya hikayat atau puisi klasik yang menampilkan gaya bahasa arkaik dan penuh kiasan, khususnya bagi menggambarkan tindakan atau pandangan; tidak sesuai dalam penggunaan moden kerana maknanya kurang dikenali dan tidak digunakan dalam bahasa Melayu kontemporari.', 'Lihat', 'togan.mp3', 'togan.jpg'),
('uba', 'Bubur sagu dibiarkan mendak dalam uba tanah liat warisan nenek moyang', '[u.bɑ]', 'Sesuai digunakan dalam konteks sastera tradisional, etnografi, atau perbincangan budaya material Melayu yang menekankan peralatan warisan; tidak sesuai digunakan dalam bahasa harian moden kerana perkataan ini sudah digantikan dengan istilah seperti pasu tanah liat atau bekas sagu.', 'Pasu untuk mengendapkan bubur sagu', 'uba.mp3', 'uba.jpg'),
('uktab', 'Uktab berlegar di angkasa, memburu mangsa di batas sawah nan lengang', '[uk.tɑb]', 'Sesuai digunakan dalam karya sastera klasik atau penulisan kreatif yang menggambarkan suasana alam dan fauna Melayu lama; sesuai juga dalam konteks zoologi tradisional atau cerita rakyat, namun tidak sesuai dalam penggunaan akademik moden kerana istilah ini kurang dikenali.', 'Helang belalang (burung)', 'uktab.mp3', 'uktab.jpg'),
('usam', 'Lukisan lama itu kelihatan usam, namun tetap tersimpan nilai warisan yang mendalam', '[u.sɑm]', 'Sesuai digunakan dalam bidang kesusasteraan dan seni visual untuk menggambarkan sesuatu yang pudar, lusuh, atau berusia dalam konteks estetik; masih boleh digunakan dalam bahasa moden yang bersifat puitis, tetapi jarang digunakan dalam komunikasi umum.', 'Adj (bukan warna) pudar dan kelihatan kurang menarik', 'usam.mp3', 'usam.jpg'),
('wardi', 'Dengan wardi raja, hulubalang segera mengatur barisan menuju medan tempur', '[wɑr.di]', 'Sesuai digunakan dalam karya hikayat atau teks sejarah yang melibatkan konteks pemerintahan dan ketenteraan zaman silam; tidak sesuai digunakan dalam konteks pentadbiran moden kerana kini telah digantikan dengan perkataan seperti perintah atau arahan.', 'Perintah; ordi', 'wardi.mp3', 'wardi.jpg'),
('wartawati', 'Wartawati itu melakar berita dengan pena ibarat mata pedang, menyampaikan hal ehwal negeri kepada rakyat jelata', '[wɑr.tɑ.wɑ.ti]', 'Sesuai digunakan dalam bidang kewartawanan dan kesusasteraan moden untuk menggambarkan penulis berita wanita; tidak bertentangan dengan garis panduan MCMC dan wajar digunakan dalam naskhah Melayu kontemporari.', 'Wartawan wanita', 'wartawati.mp3', 'wartawati.jpg'),
('zamin', 'Di zamin yang subur ini, segala tamadun bersemi di bawah naungan raja yang adil bijaksana', '[zɑ.min]', 'Sesuai digunakan dalam konteks sejarah, kesusasteraan klasik, atau naskhah Melayu lama bagi menggambarkan negeri atau wilayah di bawah pemerintahan raja; tidak sesuai untuk teks rasmi moden kecuali bernuansa sastera.', 'Negeri atau tanah', 'zamin.mp3', 'zamin.jpg'),
('zamindar', 'Zamindar memerintah tanah pusaka dengan kuasa dan kebijaksanaan, menjaga rakyat jelata di bawah naungannya', '[zɑ.min.dɑr]', 'Sesuai digunakan dalam penulisan sejarah atau kesusasteraan Melayu yang menyentuh sistem feudal dan tanah jajahan; tidak sesuai dalam konteks pentadbiran moden namun bernilai tinggi dalam karya naratif tradisional.', 'Tuan tanah', 'zamindar.mp3', 'zamindar.jpg'),
('zigurat', 'Di puncak zigurat yang menjulang tinggi, para pendita menghadap langit mencari petunjuk dari bintang-bintang purba', '[zi.gu.rɑt]', 'Sesuai digunakan dalam penulisan sejarah, arkeologi, dan kesusasteraan purba bagi menggambarkan seni bina keagamaan tamadun Mesopotamia. Istilah ini boleh digunakan dalam karya ilmiah, pameran muzium, atau teks sastera yang bernuansa tamadun kuno, terutamanya untuk menunjukkan keagungan, spiritualiti, atau simbolisme ketuhanan pada masa silam.', 'Menara srp batu-bata berbentuk segi empat tepa tyg dibina berteres dan bertingkat-tingkat pd zaman Mesopotamia kuno, yg biasanya dijadikan tempat penyembahan atau tempat pengamatan bintang', 'zigurat.mp3', 'zigurat.jpg');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `kamus_arkaik`
--
ALTER TABLE `kamus_arkaik`
  ADD PRIMARY KEY (`perkataan`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
